name: Build Blueprint Index
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build blueprint index
      run: |
        # Create _data directory for Jekyll
        mkdir -p _data
        
        # Generate blueprints.json from directory structure
        node scripts/build-index.js
        
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
